name: 'Libraries Exhibitions Recipe'
description: 'Basic needs and structure for Exhibitions.'
type: module
install:
  # Contrib
  - media_folders
  - linked_field
  - ui_patterns
  - better_exposed_filters
